version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/mey
    overwrite: yes

permissions:
  - object: /home/ubuntu/mey
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
