spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongToEnsureSecurityAndValidityForHmacSha256Algorithm}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)


openai:
  api:
    key: ${OPENAI_API_KEY:dummy}
    url: https://api.openai.com/v1/chat/completions

tmap:
  transit:
    base-url: https://apis.openapi.sk.com/transit
    app-key: ${TMAP_APP_KEY:dummy}
    lang: 0 # 0=Korean
    count: 1
