spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data-mysql.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  level:
    com.mey.backend: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.tool.schema.internal: warn
    org.hibernate.sql: warn
    org.springframework.web.servlet.DispatcherServlet: ERROR
    org.springframework.security.web.FilterChainProxy: ERROR
