spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)
