spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)

openai:
  api:
    key: ${OPENAI_API_KEY:dummy}
    url: https://api.openai.com/v1/chat/completions

tmap:
  transit:
    base-url: https://apis.openapi.sk.com/transit
    app-key: ${TMAP_APP_KEY:dummy}
    lang: 0 # 0=Korean
    count: 1

tourapi:
  service-key: ${TOURAPI_SERVICE_KEY}
  mobile-os: "ETC"
  mobile-app: "KRoute"
  base:
    related: http://apis.data.go.kr/B551011/TarRlteTarService1
    kor: http://apis.data.go.kr/B551011/KorService2
    eng: http://apis.data.go.kr/B551011/EngService2
    jpn: http://apis.data.go.kr/B551011/JpnService2
    chs: http://apis.data.go.kr/B551011/ChsService2

cloud:
  aws:
    s3:
      bucket: mey-cd-bucket
      path:
        profile: profile
        place: place
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

# Chatbot 다국어 설정
chatbot:
  language:
    supported: ko,en,ja,zh  # 지원하는 언어 목록
    fallback: en             # 지원되지 않는 언어의 fallback 언어 (일본어/중국어 → 영어)
    default: ko              # 기본 언어