spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: dev

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)

openai:
  api:
    key: ${OPENAI_API_KEY:dummy}
    url: https://api.openai.com/v1/chat/completions

tmap:
  transit:
    base-url: https://apis.openapi.sk.com/transit
    app-key: ${TMAP_APP_KEY:dummy}
    lang: 0 # 0=Korean
    count: 1

cloud:
  aws:
    s3:
      bucket: mey-cd-bucket
      path:
        profile: profile
        place: place
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
