spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
#      data-locations: classpath:sql/data-mysql.sql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format-sql: true
        hbm2ddl:
          auto: create-drop

logging:
  level:
    com.mey.backend: DEBUG
    org.springframework.web: DEBUG
