name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      DEPLOYMENT_APPLICATION_NAME: MEY-WAS
      DEPLOYMENT_GROUP_NAME: MEY-CD
      PROJECT_NAME: MEY
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TMAP_APP_KEY: ${{ secrets.TMAP_APP_KEY }}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      TOURAPI_SERVICE_KEY: ${{ secrets.TOURAPI_SERVICE_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
